const MUTATION_TYPES = {
  SET_BACKLOG_ID: "SET_BACKLOG_ID",
  GET_BACKLOG_REQUEST: "GET_BACKLOG_REQUEST",
  GET_BACKLOG_SUCCESS: "GET_BACKLOG_SUCCESS",
  API_FAILURE: "API_FAILURE",
  MOVE_ITEM: "MOVE_ITEM",
  MOVE_COLUMN: "MOVE_COLUMN",
  SET_COLUMNS: "SET_COLUMNS",
  SET_MODAL_INFO: "SET_MODAL_INFO",
  CLOSE_MODAL: "CLOSE_MODAL",
  ADD_TAG_SUCCESS: "ADD_TAG_SUCCESS",
  TOGGLE_TAG: "TOGGLE_TAG",
  SET_TAG_NAME: "SET_TAG_NAME",
  SHOW_TAG_FIELD: "SHOW_TAG_FIELD",
  EDIT_POINT: "EDIT_POINT",
  ADD_USER: "ADD_USER",
  CHANGE_USER: "CHANGE_USER",
  ITEM_CREATE_SUCCESS: "ITEM_CREATE_SUCCESS",
  ITEM_DELETE_SUCCESS: "ITEM_CREATE_SUCCESS",
  ITEM_UPDATE_SUCCESS: "ITEM_UPDATE_SUCCESS",
  EDIT_ITEM_NAME: "EDIT_ITEM_NAME",
  FORMAT_MODAL_INFO: "FORMAT_MODAL_INFO"
};
export default MUTATION_TYPES;
