const MUTATION_TYPES = {
  GET_BACKLOG_REQUEST: "GET_BACKLOG_REQUEST",
  GET_BACKLOG_SUCCESS: "GET_BACKLOG_SUCCESS",
  GET_BACKLOG_FAILURE: "GET_BACKLOG_FAILURE",
  MOVE_ITEM: "MOVE_ITEM",
  MOVE_COLUMN: "MOVE_COLUMN",
  SET_COLUMNS: "SET_COLUMNS"
};
export default MUTATION_TYPES;
